stateDiagram-v2
    state "mul_by_5" as simulation_mul_by_5
    state "@m5_loop" as simulation__m5_loop
    state "@m5_done" as simulation__m5_done
    state "@m5_cap" as simulation__m5_cap
    state "mul_by_10" as simulation_mul_by_10
    state "@m10_loop" as simulation__m10_loop
    state "@m10_done" as simulation__m10_done
    state "@m10_cap" as simulation__m10_cap
    state "mul_by_20" as simulation_mul_by_20
    state "@m20_loop" as simulation__m20_loop
    state "@m20_done" as simulation__m20_done
    state "@m20_cap" as simulation__m20_cap
    state "mul_by_50" as simulation_mul_by_50
    state "@m50_loop" as simulation__m50_loop
    state "@m50_done" as simulation__m50_done
    state "@m50_cap" as simulation__m50_cap
    state "mul_by_2" as simulation_mul_by_2
    state "@m2_cap" as simulation__m2_cap
    state "mul_by_3" as simulation_mul_by_3
    state "@m3_cap" as simulation__m3_cap
    state "add_to_jobs" as simulation_add_to_jobs
    state "@atj_store" as simulation__atj_store
    state "add_to_revenue" as simulation_add_to_revenue
    state "@atr_done" as simulation__atr_done
    state "add_to_cost" as simulation_add_to_cost
    state "@atc_done" as simulation__atc_done
    state "add_to_land_value" as simulation_add_to_land_value
    state "@atl_done" as simulation__atl_done
    state "add_to_worker_supply" as simulation_add_to_worker_supply
    state "@atw_store" as simulation__atw_store
    state "add_a_to_tmp3" as simulation_add_a_to_tmp3
    state "@a3_store" as simulation__a3_store
    state "clear_map_buffer" as simulation_clear_map_buffer
    state "@cmb_page" as simulation__cmb_page
    state "@cmb_loop" as simulation__cmb_loop
    state "@cmb_rem" as simulation__cmb_rem
    state "clear_sim_maps" as simulation_clear_sim_maps
    state "copy_map_buffer" as simulation_copy_map_buffer
    state "@cpb_page" as simulation__cpb_page
    state "@cpb_loop" as simulation__cpb_loop
    state "@cpb_rem" as simulation__cpb_rem
    state "clear_segment_totals" as simulation_clear_segment_totals
    state "@cst_loop" as simulation__cst_loop
    state "clear_segment_used" as simulation_clear_segment_used
    state "@csu_loop" as simulation__csu_loop
    state "clear_road_segment_state" as simulation_clear_road_segment_state
    state "add_segment_to_pack" as simulation_add_segment_to_pack
    state "@astp_check_high" as simulation__astp_check_high
    state "@astp_store_low" as simulation__astp_store_low
    state "@astp_store_high" as simulation__astp_store_high
    state "@astp_done" as simulation__astp_done
    state "collect_adjacent_segments" as simulation_collect_adjacent_segments
    state "@cas_south" as simulation__cas_south
    state "@cas_east" as simulation__cas_east
    state "@cas_west" as simulation__cas_west
    state "@cas_done" as simulation__cas_done
    state "update_building_segment_at" as simulation_update_building_segment_at
    state "@ubsa_clear" as simulation__ubsa_clear
    state "rebuild_building_segments" as simulation_rebuild_building_segments
    state "@rbs_row" as simulation__rbs_row
    state "@rbs_col" as simulation__rbs_col
    state "@rbs_next_row" as simulation__rbs_next_row
    state "@rbs_done" as simulation__rbs_done
    state "touches_current_segment" as simulation_touches_current_segment
    state "@tcs_south" as simulation__tcs_south
    state "@tcs_east" as simulation__tcs_east
    state "@tcs_west" as simulation__tcs_west
    state "@tcs_no" as simulation__tcs_no
    state "@tcs_yes" as simulation__tcs_yes
    state "expand_temp_segment" as simulation_expand_temp_segment
    state "@ets_pass" as simulation__ets_pass
    state "@ets_row" as simulation__ets_row
    state "@ets_col" as simulation__ets_col
    state "@ets_roadlike" as simulation__ets_roadlike
    state "@ets_next" as simulation__ets_next
    state "@ets_next_row" as simulation__ets_next_row
    state "@ets_pass_done" as simulation__ets_pass_done
    state "choose_segment_id_for_temp" as simulation_choose_segment_id_for_temp
    state "@csit_row" as simulation__csit_row
    state "@csit_col" as simulation__csit_col
    state "@csit_store_old" as simulation__csit_store_old
    state "@csit_next" as simulation__csit_next
    state "@csit_next_row" as simulation__csit_next_row
    state "@csit_choose" as simulation__csit_choose
    state "@csit_find_free" as simulation__csit_find_free
    state "@csit_find_loop" as simulation__csit_find_loop
    state "@csit_use_x" as simulation__csit_use_x
    state "@csit_use" as simulation__csit_use
    state "relabel_temp_segment" as simulation_relabel_temp_segment
    state "@rts_row" as simulation__rts_row
    state "@rts_col" as simulation__rts_col
    state "@rts_next" as simulation__rts_next
    state "@rts_next_row" as simulation__rts_next_row
    state "@rts_done" as simulation__rts_done
    state "rebuild_road_segments" as simulation_rebuild_road_segments
    state "@rrs_row" as simulation__rrs_row
    state "@rrs_col" as simulation__rrs_col
    state "@rrs_roadlike" as simulation__rrs_roadlike
    state "@rrs_next" as simulation__rrs_next
    state "@rrs_next_row" as simulation__rrs_next_row
    state "@rrs_done" as simulation__rrs_done
    state "load_metric_at" as simulation_load_metric_at
    state "store_metric_at" as simulation_store_metric_at
    state "stamp_radius_add" as simulation_stamp_radius_add
    state "@sra_row_lo_ok" as simulation__sra_row_lo_ok
    state "@sra_row_hi_ok" as simulation__sra_row_hi_ok
    state "@sra_col_lo_ok" as simulation__sra_col_lo_ok
    state "@sra_col_hi_ok" as simulation__sra_col_hi_ok
    state "@sra_row_loop" as simulation__sra_row_loop
    state "@sra_ptr_ok" as simulation__sra_ptr_ok
    state "@sra_col_loop" as simulation__sra_col_loop
    state "@sra_store" as simulation__sra_store
    state "region_has_nonzero" as simulation_region_has_nonzero
    state "@rhn_row_lo_ok" as simulation__rhn_row_lo_ok
    state "@rhn_row_hi_ok" as simulation__rhn_row_hi_ok
    state "@rhn_col_lo_ok" as simulation__rhn_col_lo_ok
    state "@rhn_col_hi_ok" as simulation__rhn_col_hi_ok
    state "@rhn_row_loop" as simulation__rhn_row_loop
    state "@rhn_ptr_ok" as simulation__rhn_ptr_ok
    state "@rhn_col_loop" as simulation__rhn_col_loop
    state "@rhn_found" as simulation__rhn_found
    state "build_service_maps" as simulation_build_service_maps
    state "@bsm_row" as simulation__bsm_row
    state "@bsm_col" as simulation__bsm_col
    state "@bsm_police" as simulation__bsm_police
    state "@bsm_fire" as simulation__bsm_fire
    state "@bsm_house" as simulation__bsm_house
    state "@bsm_factory" as simulation__bsm_factory
    state "@bsm_next" as simulation__bsm_next
    state "@bsm_next_row" as simulation__bsm_next_row
    state "@bsm_done" as simulation__bsm_done
    state "apply_neighbor_value_effect" as simulation_apply_neighbor_value_effect
    state "@anv_road" as simulation__anv_road
    state "@anv_house" as simulation__anv_house
    state "@anv_factory" as simulation__anv_factory
    state "@anv_sub_factory" as simulation__anv_sub_factory
    state "@anv_park" as simulation__anv_park
    state "@anv_power" as simulation__anv_power
    state "@anv_sub_power" as simulation__anv_sub_power
    state "@anv_police" as simulation__anv_police
    state "@anv_service" as simulation__anv_service
    state "@anv_done" as simulation__anv_done
    state "compute_tile_value_at" as simulation_compute_tile_value_at
    state "@ctv_road" as simulation__ctv_road
    state "@ctv_house" as simulation__ctv_house
    state "@ctv_factory" as simulation__ctv_factory
    state "@ctv_park" as simulation__ctv_park
    state "@ctv_power" as simulation__ctv_power
    state "@ctv_police" as simulation__ctv_police
    state "@ctv_fire" as simulation__ctv_fire
    state "@ctv_base_done" as simulation__ctv_base_done
    state "@ctv_effects" as simulation__ctv_effects
    state "@ctv_public_safety" as simulation__ctv_public_safety
    state "@ctv_neighbors" as simulation__ctv_neighbors
    state "@ctv_south" as simulation__ctv_south
    state "@ctv_east" as simulation__ctv_east
    state "@ctv_west" as simulation__ctv_west
    state "@ctv_need_road" as simulation__ctv_need_road
    state "@ctv_check_road" as simulation__ctv_check_road
    state "@ctv_sub_no_road" as simulation__ctv_sub_no_road
    state "@ctv_clamp" as simulation__ctv_clamp
    state "@ctv_done" as simulation__ctv_done
    state "analyze_city_tiles" as simulation_analyze_city_tiles
    state "@act_row" as simulation__act_row
    state "@act_col" as simulation__act_col
    state "@act_check_factory" as simulation__act_check_factory
    state "@act_check_police" as simulation__act_check_police
    state "@act_check_fire" as simulation__act_check_fire
    state "@act_other" as simulation__act_other
    state "@act_house" as simulation__act_house
    state "@act_value_loop" as simulation__act_value_loop
    state "@act_store_park" as simulation__act_store_park
    state "@act_police" as simulation__act_police
    state "@act_store_police" as simulation__act_store_police
    state "@act_fire" as simulation__act_fire
    state "@act_store_fire" as simulation__act_store_fire
    state "@act_worker" as simulation__act_worker
    state "@act_factory" as simulation__act_factory
    state "@act_police_jobs" as simulation__act_police_jobs
    state "@act_fire_jobs" as simulation__act_fire_jobs
    state "@act_next" as simulation__act_next
    state "@act_next_row" as simulation__act_next_row
    state "@act_done" as simulation__act_done
    state "add_to_component_jobs" as simulation_add_to_component_jobs
    state "@acj_store" as simulation__acj_store
    state "add_to_component_workers" as simulation_add_to_component_workers
    state "@acw_store" as simulation__acw_store
    state "touches_current_road_component" as simulation_touches_current_road_component
    state "@trc_south" as simulation__trc_south
    state "@trc_east" as simulation__trc_east
    state "@trc_west" as simulation__trc_west
    state "@trc_no" as simulation__trc_no
    state "@trc_yes" as simulation__trc_yes
    state "expand_current_road_component" as simulation_expand_current_road_component
    state "@erc_pass" as simulation__erc_pass
    state "@erc_row" as simulation__erc_row
    state "@erc_col" as simulation__erc_col
    state "@erc_roadlike" as simulation__erc_roadlike
    state "@erc_next" as simulation__erc_next
    state "@erc_next_row" as simulation__erc_next_row
    state "@erc_pass_done" as simulation__erc_pass_done
    state "mark_current_road_component_processed" as simulation_mark_current_road_component_processed
    state "@mrc_row" as simulation__mrc_row
    state "@mrc_col" as simulation__mrc_col
    state "@mrc_next" as simulation__mrc_next
    state "@mrc_next_row" as simulation__mrc_next_row
    state "@mrc_done" as simulation__mrc_done
    state "score_current_road_component" as simulation_score_current_road_component
    state "@src_row" as simulation__src_row
    state "@src_col" as simulation__src_col
    state "@src_not_empty" as simulation__src_not_empty
    state "@src_not_water" as simulation__src_not_water
    state "@src_not_tree" as simulation__src_not_tree
    state "@src_connected" as simulation__src_connected
    state "@src_factory" as simulation__src_factory
    state "@src_police" as simulation__src_police
    state "@src_fire" as simulation__src_fire
    state "@src_next" as simulation__src_next
    state "@src_next_row" as simulation__src_next_row
    state "@src_totals" as simulation__src_totals
    state "@src_use_workers" as simulation__src_use_workers
    state "@src_add_employed" as simulation__src_add_employed
    state "@src_done" as simulation__src_done
    state "analyze_road_networks" as simulation_analyze_road_networks
    state "@arn_row" as simulation__arn_row
    state "@arn_col" as simulation__arn_col
    state "@arn_has_segments" as simulation__arn_has_segments
    state "@arn_check_factory" as simulation__arn_check_factory
    state "@arn_check_police" as simulation__arn_check_police
    state "@arn_check_fire" as simulation__arn_check_fire
    state "@arn_next" as simulation__arn_next
    state "@arn_next_row" as simulation__arn_next_row
    state "@arn_totals" as simulation__arn_totals
    state "@arn_seg_loop" as simulation__arn_seg_loop
    state "@arn_use_workers" as simulation__arn_use_workers
    state "@arn_add_emp" as simulation__arn_add_emp
    state "@arn_seg_next" as simulation__arn_seg_next
    state "@arn_done" as simulation__arn_done
    state "add_workers_for_segments" as simulation_add_workers_for_segments
    state "@awfs_store_low" as simulation__awfs_store_low
    state "@awfs_high" as simulation__awfs_high
    state "@awfs_store_high" as simulation__awfs_store_high
    state "@awfs_done" as simulation__awfs_done
    state "add_jobs_for_segments" as simulation_add_jobs_for_segments
    state "@ajfs_store_low" as simulation__ajfs_store_low
    state "@ajfs_high" as simulation__ajfs_high
    state "@ajfs_store_high" as simulation__ajfs_store_high
    state "@ajfs_done" as simulation__ajfs_done
    state "run_simulation" as simulation_run_simulation
    state "@pwr_police" as simulation__pwr_police
    state "@pwr_fire" as simulation__pwr_fire
    state "@pwr_store" as simulation__pwr_store
    state "@jobs" as simulation__jobs
    state "@jobs_overlap_ready" as simulation__jobs_overlap_ready
    state "@all_employed" as simulation__all_employed
    state "@crime" as simulation__crime
    state "@crime_cap" as simulation__crime_cap
    state "@crime_blackout" as simulation__crime_blackout
    state "@crime_store_blackout" as simulation__crime_store_blackout
    state "@crime_police" as simulation__crime_police
    state "@crime_sub_police" as simulation__crime_sub_police
    state "@crime_fire" as simulation__crime_fire
    state "@crime_sub_fire" as simulation__crime_sub_fire
    state "@crime_parks" as simulation__crime_parks
    state "@crime_sub_parks" as simulation__crime_sub_parks
    state "@crime_done" as simulation__crime_done
    state "@happiness" as simulation__happiness
    state "@hap_store_parks" as simulation__hap_store_parks
    state "@hap_store_police" as simulation__hap_store_police
    state "@hap_store_fire" as simulation__hap_store_fire
    state "@hap_store_value" as simulation__hap_store_value
    state "@hap_sub_unemp" as simulation__hap_sub_unemp
    state "@hap_job_bonus" as simulation__hap_job_bonus
    state "@hap_store_bonus" as simulation__hap_store_bonus
    state "@hap_blackout" as simulation__hap_blackout
    state "@hap_sub_blackout" as simulation__hap_sub_blackout
    state "@hap_crime" as simulation__hap_crime
    state "@hap_sub_crime" as simulation__hap_sub_crime
    state "@economy" as simulation__economy
    state "@apply_net" as simulation__apply_net
    state "@money_floor_ok" as simulation__money_floor_ok
    state "@money_ceil_ok" as simulation__money_ceil_ok
    state "@pop_jobs_ok" as simulation__pop_jobs_ok
    state "@pop_target_ready" as simulation__pop_target_ready
    state "@pop_shrink" as simulation__pop_shrink
    state "@pop_do_shrink" as simulation__pop_do_shrink
    state "@pop_balance" as simulation__pop_balance
    state "@pop_done" as simulation__pop_done
    state "@no_year" as simulation__no_year

    [*] --> simulation_mul_by_5
    simulation_mul_by_5 --> simulation__m5_done : Branch BEQ
    simulation_mul_by_5 --> simulation__m5_loop : fallthrough
    simulation__m5_loop --> simulation__m5_cap : Branch BCS
    simulation__m5_loop --> simulation__m5_loop : Branch BNE
    simulation__m5_loop --> simulation__m5_done : fallthrough
    simulation_mul_by_10 --> simulation__m10_done : Branch BEQ
    simulation_mul_by_10 --> simulation__m10_loop : fallthrough
    simulation__m10_loop --> simulation__m10_cap : Branch BCS
    simulation__m10_loop --> simulation__m10_loop : Branch BNE
    simulation__m10_loop --> simulation__m10_done : fallthrough
    simulation_mul_by_20 --> simulation__m20_done : Branch BEQ
    simulation_mul_by_20 --> simulation__m20_loop : fallthrough
    simulation__m20_loop --> simulation__m20_cap : Branch BCS
    simulation__m20_loop --> simulation__m20_loop : Branch BNE
    simulation__m20_loop --> simulation__m20_done : fallthrough
    simulation_mul_by_50 --> simulation__m50_done : Branch BEQ
    simulation_mul_by_50 --> simulation__m50_loop : fallthrough
    simulation__m50_loop --> simulation__m50_cap : Branch BCS
    simulation__m50_loop --> simulation__m50_loop : Branch BNE
    simulation__m50_loop --> simulation__m50_done : fallthrough
    simulation_mul_by_2 --> simulation__m2_cap : Branch BCS
    simulation_mul_by_3 --> simulation__m3_cap : Branch BCS
    simulation_mul_by_3 --> simulation__m3_cap : Branch BCS
    simulation_add_to_jobs --> simulation__atj_store : Branch BCC
    simulation_add_to_jobs --> simulation__atj_store : fallthrough
    simulation_add_to_revenue --> simulation__atr_done : Branch BCC
    simulation_add_to_revenue --> simulation__atr_done : fallthrough
    simulation_add_to_cost --> simulation__atc_done : Branch BCC
    simulation_add_to_cost --> simulation__atc_done : fallthrough
    simulation_add_to_land_value --> simulation__atl_done : Branch BCC
    simulation_add_to_land_value --> simulation__atl_done : Branch BNE
    simulation_add_to_land_value --> simulation__atl_done : fallthrough
    simulation_add_to_worker_supply --> simulation__atw_store : Branch BCC
    simulation_add_to_worker_supply --> simulation__atw_store : fallthrough
    simulation_add_a_to_tmp3 --> simulation__a3_store : Branch BCC
    simulation_add_a_to_tmp3 --> simulation__a3_store : fallthrough
    simulation_clear_map_buffer --> simulation__cmb_page : fallthrough
    simulation__cmb_page --> simulation__cmb_loop : fallthrough
    simulation__cmb_loop --> simulation__cmb_loop : Branch BNE
    simulation__cmb_loop --> simulation__cmb_page : Branch BNE
    simulation__cmb_loop --> simulation__cmb_rem : fallthrough
    simulation__cmb_rem --> simulation__cmb_rem : Branch BNE
    simulation_clear_sim_maps --> simulation_clear_map_buffer : Call clear_map_buffer
    simulation_clear_sim_maps --> simulation_clear_map_buffer : Call clear_map_buffer
    simulation_clear_sim_maps --> simulation_clear_map_buffer : Call clear_map_buffer
    simulation_clear_sim_maps --> simulation_clear_map_buffer : Call clear_map_buffer
    simulation_clear_sim_maps --> simulation_clear_map_buffer : Call clear_map_buffer
    simulation_clear_sim_maps --> simulation_clear_map_buffer : Call clear_map_buffer
    simulation_copy_map_buffer --> simulation__cpb_page : fallthrough
    simulation__cpb_page --> simulation__cpb_loop : fallthrough
    simulation__cpb_loop --> simulation__cpb_loop : Branch BNE
    simulation__cpb_loop --> simulation__cpb_page : Branch BNE
    simulation__cpb_loop --> simulation__cpb_rem : fallthrough
    simulation__cpb_rem --> simulation__cpb_rem : Branch BNE
    simulation_clear_segment_totals --> simulation__cst_loop : fallthrough
    simulation__cst_loop --> simulation__cst_loop : Branch BPL
    simulation_clear_segment_used --> simulation__csu_loop : fallthrough
    simulation__csu_loop --> simulation__csu_loop : Branch BPL
    simulation_clear_road_segment_state --> simulation_clear_map_buffer : Call clear_map_buffer
    simulation_clear_road_segment_state --> simulation_clear_map_buffer : Call clear_map_buffer
    simulation_clear_road_segment_state --> simulation_clear_map_buffer : Call clear_map_buffer
    simulation_clear_road_segment_state --> simulation_clear_segment_totals : Call clear_segment_totals
    simulation_clear_road_segment_state --> simulation_clear_segment_used : Call clear_segment_used
    simulation_add_segment_to_pack --> simulation__astp_done : Branch BCS
    simulation_add_segment_to_pack --> simulation__astp_done : Branch BEQ
    simulation_add_segment_to_pack --> simulation__astp_store_low : Branch BEQ
    simulation_add_segment_to_pack --> simulation__astp_done : Branch BEQ
    simulation_add_segment_to_pack --> simulation__astp_store_high : Branch BEQ
    simulation_add_segment_to_pack --> simulation__astp_done : Branch BEQ
    simulation_add_segment_to_pack --> simulation__astp_check_high : Branch BCC
    simulation__astp_check_high --> simulation__astp_done : Branch BCC
    simulation__astp_check_high --> simulation__astp_done : Branch BEQ
    simulation__astp_store_high --> simulation__astp_done : fallthrough
    simulation_collect_adjacent_segments --> simulation__cas_south : Branch BEQ
    simulation_collect_adjacent_segments --> simulation_load_metric_at : Call load_metric_at
    simulation_collect_adjacent_segments --> simulation_add_segment_to_pack : Call add_segment_to_pack
    simulation_collect_adjacent_segments --> simulation__cas_south : fallthrough
    simulation__cas_south --> simulation__cas_east : Branch BCS
    simulation__cas_south --> simulation_load_metric_at : Call load_metric_at
    simulation__cas_south --> simulation_add_segment_to_pack : Call add_segment_to_pack
    simulation__cas_south --> simulation__cas_east : fallthrough
    simulation__cas_east --> simulation__cas_west : Branch BCS
    simulation__cas_east --> simulation_load_metric_at : Call load_metric_at
    simulation__cas_east --> simulation_add_segment_to_pack : Call add_segment_to_pack
    simulation__cas_east --> simulation__cas_west : fallthrough
    simulation__cas_west --> simulation__cas_done : Branch BEQ
    simulation__cas_west --> simulation_load_metric_at : Call load_metric_at
    simulation__cas_west --> simulation_add_segment_to_pack : Call add_segment_to_pack
    simulation__cas_west --> simulation__cas_done : fallthrough
    simulation_update_building_segment_at --> map_get_tile : Call get_tile
    simulation_update_building_segment_at --> simulation__ubsa_clear : Branch BCC
    simulation_update_building_segment_at --> simulation__ubsa_clear : Branch BCS
    simulation_update_building_segment_at --> simulation_collect_adjacent_segments : Call collect_adjacent_segments
    simulation_update_building_segment_at --> simulation_store_metric_at : Jmp JMP
    simulation_update_building_segment_at --> simulation__ubsa_clear : fallthrough
    simulation__ubsa_clear --> simulation_store_metric_at : Jmp JMP
    simulation__ubsa_clear --> simulation_rebuild_building_segments : fallthrough
    simulation_rebuild_building_segments --> simulation__rbs_row : fallthrough
    simulation__rbs_row --> simulation__rbs_col : fallthrough
    simulation__rbs_col --> simulation_update_building_segment_at : Call update_building_segment_at
    simulation__rbs_col --> simulation__rbs_next_row : Branch BEQ
    simulation__rbs_col --> simulation__rbs_col : Jmp JMP
    simulation__rbs_col --> simulation__rbs_next_row : fallthrough
    simulation__rbs_next_row --> simulation__rbs_done : Branch BEQ
    simulation__rbs_next_row --> simulation__rbs_row : Jmp JMP
    simulation__rbs_next_row --> simulation__rbs_done : fallthrough
    simulation_touches_current_segment --> simulation__tcs_south : Branch BEQ
    simulation_touches_current_segment --> simulation_load_metric_at : Call load_metric_at
    simulation_touches_current_segment --> simulation__tcs_yes : Branch BEQ
    simulation_touches_current_segment --> simulation__tcs_south : fallthrough
    simulation__tcs_south --> simulation__tcs_east : Branch BCS
    simulation__tcs_south --> simulation_load_metric_at : Call load_metric_at
    simulation__tcs_south --> simulation__tcs_yes : Branch BEQ
    simulation__tcs_south --> simulation__tcs_east : fallthrough
    simulation__tcs_east --> simulation__tcs_west : Branch BCS
    simulation__tcs_east --> simulation_load_metric_at : Call load_metric_at
    simulation__tcs_east --> simulation__tcs_yes : Branch BEQ
    simulation__tcs_east --> simulation__tcs_west : fallthrough
    simulation__tcs_west --> simulation__tcs_no : Branch BEQ
    simulation__tcs_west --> simulation_load_metric_at : Call load_metric_at
    simulation__tcs_west --> simulation__tcs_yes : Branch BEQ
    simulation__tcs_west --> simulation__tcs_no : fallthrough
    simulation_expand_temp_segment --> simulation__ets_pass : fallthrough
    simulation__ets_pass --> simulation__ets_row : fallthrough
    simulation__ets_row --> simulation__ets_col : fallthrough
    simulation__ets_col --> map_get_tile : Call get_tile
    simulation__ets_col --> simulation__ets_roadlike : Branch BEQ
    simulation__ets_col --> simulation__ets_next : Branch BNE
    simulation__ets_col --> simulation__ets_roadlike : fallthrough
    simulation__ets_roadlike --> simulation_load_metric_at : Call load_metric_at
    simulation__ets_roadlike --> simulation__ets_next : Branch BNE
    simulation__ets_roadlike --> simulation_touches_current_segment : Call touches_current_segment
    simulation__ets_roadlike --> simulation__ets_next : Branch BEQ
    simulation__ets_roadlike --> simulation_store_metric_at : Call store_metric_at
    simulation__ets_roadlike --> simulation__ets_next : fallthrough
    simulation__ets_next --> simulation__ets_next_row : Branch BEQ
    simulation__ets_next --> simulation__ets_col : Jmp JMP
    simulation__ets_next --> simulation__ets_next_row : fallthrough
    simulation__ets_next_row --> simulation__ets_pass_done : Branch BEQ
    simulation__ets_next_row --> simulation__ets_row : Jmp JMP
    simulation__ets_next_row --> simulation__ets_pass_done : fallthrough
    simulation__ets_pass_done --> simulation__ets_pass : Branch BNE
    simulation_choose_segment_id_for_temp --> simulation__csit_row : fallthrough
    simulation__csit_row --> simulation__csit_col : fallthrough
    simulation__csit_col --> simulation_load_metric_at : Call load_metric_at
    simulation__csit_col --> simulation__csit_next : Branch BNE
    simulation__csit_col --> simulation_load_metric_at : Call load_metric_at
    simulation__csit_col --> simulation__csit_next : Branch BEQ
    simulation__csit_col --> simulation__csit_next : Branch BCS
    simulation__csit_col --> simulation__csit_store_old : Branch BEQ
    simulation__csit_col --> simulation__csit_store_old : Branch BCS
    simulation__csit_col --> simulation__csit_store_old : Branch BEQ
    simulation__csit_col --> simulation__csit_next : Branch BCS
    simulation__csit_col --> simulation__csit_store_old : fallthrough
    simulation__csit_store_old --> simulation__csit_next : fallthrough
    simulation__csit_next --> simulation__csit_next_row : Branch BEQ
    simulation__csit_next --> simulation__csit_col : Jmp JMP
    simulation__csit_next --> simulation__csit_next_row : fallthrough
    simulation__csit_next_row --> simulation__csit_choose : Branch BEQ
    simulation__csit_next_row --> simulation__csit_row : Jmp JMP
    simulation__csit_next_row --> simulation__csit_choose : fallthrough
    simulation__csit_choose --> simulation__csit_find_free : Branch BEQ
    simulation__csit_choose --> simulation__csit_find_free : Branch BNE
    simulation__csit_choose --> simulation__csit_use : Branch BNE
    simulation__csit_choose --> simulation__csit_find_free : fallthrough
    simulation__csit_find_free --> simulation__csit_find_loop : fallthrough
    simulation__csit_find_loop --> simulation__csit_use_x : Branch BEQ
    simulation__csit_find_loop --> simulation__csit_find_loop : Branch BNE
    simulation__csit_use_x --> simulation__csit_use : fallthrough
    simulation_relabel_temp_segment --> simulation__rts_row : fallthrough
    simulation__rts_row --> simulation__rts_col : fallthrough
    simulation__rts_col --> simulation_load_metric_at : Call load_metric_at
    simulation__rts_col --> simulation__rts_next : Branch BNE
    simulation__rts_col --> simulation_store_metric_at : Call store_metric_at
    simulation__rts_col --> simulation__rts_next : fallthrough
    simulation__rts_next --> simulation__rts_next_row : Branch BEQ
    simulation__rts_next --> simulation__rts_col : Jmp JMP
    simulation__rts_next --> simulation__rts_next_row : fallthrough
    simulation__rts_next_row --> simulation__rts_done : Branch BEQ
    simulation__rts_next_row --> simulation__rts_row : Jmp JMP
    simulation__rts_next_row --> simulation__rts_done : fallthrough
    simulation_rebuild_road_segments --> simulation_copy_map_buffer : Call copy_map_buffer
    simulation_rebuild_road_segments --> simulation_clear_map_buffer : Call clear_map_buffer
    simulation_rebuild_road_segments --> simulation_clear_segment_used : Call clear_segment_used
    simulation_rebuild_road_segments --> simulation__rrs_row : fallthrough
    simulation__rrs_row --> simulation__rrs_col : fallthrough
    simulation__rrs_col --> map_get_tile : Call get_tile
    simulation__rrs_col --> simulation__rrs_roadlike : Branch BEQ
    simulation__rrs_col --> simulation__rrs_next : Branch BNE
    simulation__rrs_col --> simulation__rrs_roadlike : fallthrough
    simulation__rrs_roadlike --> simulation_load_metric_at : Call load_metric_at
    simulation__rrs_roadlike --> simulation__rrs_next : Branch BNE
    simulation__rrs_roadlike --> simulation_store_metric_at : Call store_metric_at
    simulation__rrs_roadlike --> simulation_expand_temp_segment : Call expand_temp_segment
    simulation__rrs_roadlike --> simulation_choose_segment_id_for_temp : Call choose_segment_id_for_temp
    simulation__rrs_roadlike --> simulation_relabel_temp_segment : Call relabel_temp_segment
    simulation__rrs_roadlike --> simulation__rrs_next : fallthrough
    simulation__rrs_next --> simulation__rrs_next_row : Branch BEQ
    simulation__rrs_next --> simulation__rrs_col : Jmp JMP
    simulation__rrs_next --> simulation__rrs_next_row : fallthrough
    simulation__rrs_next_row --> simulation__rrs_done : Branch BEQ
    simulation__rrs_next_row --> simulation__rrs_row : Jmp JMP
    simulation__rrs_next_row --> simulation__rrs_done : fallthrough
    simulation__rrs_done --> simulation_rebuild_building_segments : Call rebuild_building_segments
    simulation_stamp_radius_add --> simulation__sra_row_lo_ok : Branch BCS
    simulation_stamp_radius_add --> simulation__sra_row_lo_ok : fallthrough
    simulation__sra_row_lo_ok --> simulation__sra_row_hi_ok : Branch BCC
    simulation__sra_row_lo_ok --> simulation__sra_row_hi_ok : fallthrough
    simulation__sra_row_hi_ok --> simulation__sra_col_lo_ok : Branch BCS
    simulation__sra_row_hi_ok --> simulation__sra_col_lo_ok : fallthrough
    simulation__sra_col_lo_ok --> simulation__sra_col_hi_ok : Branch BCC
    simulation__sra_col_lo_ok --> simulation__sra_col_hi_ok : fallthrough
    simulation__sra_col_hi_ok --> simulation__sra_row_loop : fallthrough
    simulation__sra_row_loop --> simulation__sra_ptr_ok : Branch BCC
    simulation__sra_row_loop --> simulation__sra_ptr_ok : fallthrough
    simulation__sra_ptr_ok --> simulation__sra_col_loop : fallthrough
    simulation__sra_col_loop --> simulation__sra_store : Branch BCC
    simulation__sra_col_loop --> simulation__sra_store : fallthrough
    simulation__sra_store --> simulation__sra_col_loop : Branch BNE
    simulation__sra_store --> simulation__sra_row_loop : Branch BCS
    simulation_region_has_nonzero --> simulation__rhn_row_lo_ok : Branch BCS
    simulation_region_has_nonzero --> simulation__rhn_row_lo_ok : fallthrough
    simulation__rhn_row_lo_ok --> simulation__rhn_row_hi_ok : Branch BCC
    simulation__rhn_row_lo_ok --> simulation__rhn_row_hi_ok : fallthrough
    simulation__rhn_row_hi_ok --> simulation__rhn_col_lo_ok : Branch BCS
    simulation__rhn_row_hi_ok --> simulation__rhn_col_lo_ok : fallthrough
    simulation__rhn_col_lo_ok --> simulation__rhn_col_hi_ok : Branch BCC
    simulation__rhn_col_lo_ok --> simulation__rhn_col_hi_ok : fallthrough
    simulation__rhn_col_hi_ok --> simulation__rhn_row_loop : fallthrough
    simulation__rhn_row_loop --> simulation__rhn_ptr_ok : Branch BCC
    simulation__rhn_row_loop --> simulation__rhn_ptr_ok : fallthrough
    simulation__rhn_ptr_ok --> simulation__rhn_col_loop : fallthrough
    simulation__rhn_col_loop --> simulation__rhn_found : Branch BNE
    simulation__rhn_col_loop --> simulation__rhn_col_loop : Branch BNE
    simulation__rhn_col_loop --> simulation__rhn_row_loop : Branch BCS
    simulation_build_service_maps --> simulation_clear_sim_maps : Call clear_sim_maps
    simulation_build_service_maps --> simulation__bsm_row : fallthrough
    simulation__bsm_row --> simulation__bsm_col : fallthrough
    simulation__bsm_col --> map_get_tile : Call get_tile
    simulation__bsm_col --> simulation__bsm_police : Branch BNE
    simulation__bsm_col --> buildings_get_tile_density_units : Call get_tile_density_units
    simulation__bsm_col --> simulation_mul_by_3 : Call mul_by_3
    simulation__bsm_col --> simulation_stamp_radius_add : Call stamp_radius_add
    simulation__bsm_col --> simulation__bsm_next : Jmp JMP
    simulation__bsm_col --> simulation__bsm_police : fallthrough
    simulation__bsm_police --> simulation__bsm_fire : Branch BNE
    simulation__bsm_police --> buildings_get_tile_density_units : Call get_tile_density_units
    simulation__bsm_police --> simulation_mul_by_2 : Call mul_by_2
    simulation__bsm_police --> simulation_stamp_radius_add : Call stamp_radius_add
    simulation__bsm_police --> simulation__bsm_next : Jmp JMP
    simulation__bsm_police --> simulation__bsm_fire : fallthrough
    simulation__bsm_fire --> simulation__bsm_house : Branch BNE
    simulation__bsm_fire --> buildings_get_tile_density_units : Call get_tile_density_units
    simulation__bsm_fire --> simulation_mul_by_2 : Call mul_by_2
    simulation__bsm_fire --> simulation_stamp_radius_add : Call stamp_radius_add
    simulation__bsm_fire --> simulation__bsm_next : Jmp JMP
    simulation__bsm_fire --> simulation__bsm_house : fallthrough
    simulation__bsm_house --> simulation__bsm_factory : Branch BNE
    simulation__bsm_house --> buildings_get_tile_density_units : Call get_tile_density_units
    simulation__bsm_house --> simulation_stamp_radius_add : Call stamp_radius_add
    simulation__bsm_house --> simulation__bsm_next : Jmp JMP
    simulation__bsm_house --> simulation__bsm_factory : fallthrough
    simulation__bsm_factory --> simulation__bsm_next : Branch BNE
    simulation__bsm_factory --> buildings_get_tile_density_units : Call get_tile_density_units
    simulation__bsm_factory --> simulation_stamp_radius_add : Call stamp_radius_add
    simulation__bsm_factory --> simulation__bsm_next : fallthrough
    simulation__bsm_next --> simulation__bsm_next_row : Branch BEQ
    simulation__bsm_next --> simulation__bsm_col : Jmp JMP
    simulation__bsm_next --> simulation__bsm_next_row : fallthrough
    simulation__bsm_next_row --> simulation__bsm_done : Branch BEQ
    simulation__bsm_next_row --> simulation__bsm_row : Jmp JMP
    simulation__bsm_next_row --> simulation__bsm_done : fallthrough
    simulation_apply_neighbor_value_effect --> simulation__anv_road : Branch BEQ
    simulation_apply_neighbor_value_effect --> simulation__anv_house : Branch BNE
    simulation_apply_neighbor_value_effect --> simulation__anv_road : fallthrough
    simulation__anv_road --> simulation_add_a_to_tmp3 : Jmp JMP
    simulation__anv_road --> simulation__anv_house : fallthrough
    simulation__anv_house --> simulation__anv_factory : Branch BNE
    simulation__anv_house --> simulation_add_a_to_tmp3 : Jmp JMP
    simulation__anv_house --> simulation__anv_factory : fallthrough
    simulation__anv_factory --> simulation__anv_park : Branch BNE
    simulation__anv_factory --> simulation__anv_sub_factory : Branch BCS
    simulation__anv_park --> simulation__anv_power : Branch BNE
    simulation__anv_park --> simulation_add_a_to_tmp3 : Jmp JMP
    simulation__anv_park --> simulation__anv_power : fallthrough
    simulation__anv_power --> simulation__anv_police : Branch BNE
    simulation__anv_power --> simulation__anv_sub_power : Branch BCS
    simulation__anv_police --> simulation__anv_service : Branch BEQ
    simulation__anv_police --> simulation__anv_done : Branch BNE
    simulation__anv_police --> simulation__anv_service : fallthrough
    simulation__anv_service --> simulation_add_a_to_tmp3 : Jmp JMP
    simulation__anv_service --> simulation__anv_done : fallthrough
    simulation_compute_tile_value_at --> map_get_tile : Call get_tile
    simulation_compute_tile_value_at --> simulation__ctv_road : Branch BEQ
    simulation_compute_tile_value_at --> simulation__ctv_house : Branch BNE
    simulation_compute_tile_value_at --> simulation__ctv_road : fallthrough
    simulation__ctv_road --> simulation__ctv_base_done : Branch BNE
    simulation__ctv_road --> simulation__ctv_house : fallthrough
    simulation__ctv_house --> simulation__ctv_factory : Branch BNE
    simulation__ctv_house --> simulation__ctv_base_done : Branch BNE
    simulation__ctv_house --> simulation__ctv_factory : fallthrough
    simulation__ctv_factory --> simulation__ctv_park : Branch BNE
    simulation__ctv_factory --> simulation__ctv_base_done : Branch BNE
    simulation__ctv_factory --> simulation__ctv_park : fallthrough
    simulation__ctv_park --> simulation__ctv_power : Branch BNE
    simulation__ctv_park --> simulation__ctv_base_done : Branch BNE
    simulation__ctv_park --> simulation__ctv_power : fallthrough
    simulation__ctv_power --> simulation__ctv_police : Branch BNE
    simulation__ctv_power --> simulation__ctv_base_done : Branch BNE
    simulation__ctv_power --> simulation__ctv_police : fallthrough
    simulation__ctv_police --> simulation__ctv_fire : Branch BNE
    simulation__ctv_police --> simulation__ctv_base_done : Branch BNE
    simulation__ctv_police --> simulation__ctv_fire : fallthrough
    simulation__ctv_fire --> simulation__ctv_base_done : Branch BNE
    simulation__ctv_fire --> simulation__ctv_base_done : fallthrough
    simulation__ctv_base_done --> simulation__ctv_effects : Branch BEQ
    simulation__ctv_base_done --> simulation__ctv_effects : Branch BCS
    simulation__ctv_base_done --> buildings_get_tile_density_units : Call get_tile_density_units
    simulation__ctv_base_done --> simulation_add_a_to_tmp3 : Call add_a_to_tmp3
    simulation__ctv_base_done --> simulation__ctv_effects : fallthrough
    simulation__ctv_effects --> simulation_load_metric_at : Call load_metric_at
    simulation__ctv_effects --> simulation_add_a_to_tmp3 : Call add_a_to_tmp3
    simulation__ctv_effects --> simulation__ctv_public_safety : Branch BEQ
    simulation__ctv_effects --> simulation__ctv_public_safety : Branch BEQ
    simulation__ctv_effects --> simulation__ctv_neighbors : Jmp JMP
    simulation__ctv_effects --> simulation__ctv_public_safety : fallthrough
    simulation__ctv_public_safety --> simulation_load_metric_at : Call load_metric_at
    simulation__ctv_public_safety --> simulation_add_a_to_tmp3 : Call add_a_to_tmp3
    simulation__ctv_public_safety --> simulation_load_metric_at : Call load_metric_at
    simulation__ctv_public_safety --> simulation_add_a_to_tmp3 : Call add_a_to_tmp3
    simulation__ctv_public_safety --> simulation__ctv_neighbors : fallthrough
    simulation__ctv_neighbors --> simulation__ctv_south : Branch BEQ
    simulation__ctv_neighbors --> map_get_tile : Call get_tile
    simulation__ctv_neighbors --> simulation_apply_neighbor_value_effect : Call apply_neighbor_value_effect
    simulation__ctv_neighbors --> simulation__ctv_south : fallthrough
    simulation__ctv_south --> simulation__ctv_east : Branch BCS
    simulation__ctv_south --> map_get_tile : Call get_tile
    simulation__ctv_south --> simulation_apply_neighbor_value_effect : Call apply_neighbor_value_effect
    simulation__ctv_south --> simulation__ctv_east : fallthrough
    simulation__ctv_east --> simulation__ctv_west : Branch BCS
    simulation__ctv_east --> map_get_tile : Call get_tile
    simulation__ctv_east --> simulation_apply_neighbor_value_effect : Call apply_neighbor_value_effect
    simulation__ctv_east --> simulation__ctv_west : fallthrough
    simulation__ctv_west --> simulation__ctv_need_road : Branch BEQ
    simulation__ctv_west --> map_get_tile : Call get_tile
    simulation__ctv_west --> simulation_apply_neighbor_value_effect : Call apply_neighbor_value_effect
    simulation__ctv_west --> simulation__ctv_need_road : fallthrough
    simulation__ctv_need_road --> simulation__ctv_check_road : Branch BEQ
    simulation__ctv_need_road --> simulation__ctv_clamp : Branch BNE
    simulation__ctv_need_road --> simulation__ctv_check_road : fallthrough
    simulation__ctv_check_road --> simulation__ctv_clamp : Branch BNE
    simulation__ctv_check_road --> simulation__ctv_sub_no_road : Branch BCS
    simulation__ctv_check_road --> simulation__ctv_clamp : Branch BEQ
    simulation__ctv_check_road --> simulation__ctv_sub_no_road : fallthrough
    simulation__ctv_sub_no_road --> simulation__ctv_clamp : fallthrough
    simulation__ctv_clamp --> simulation__ctv_done : Branch BCC
    simulation__ctv_clamp --> simulation__ctv_done : fallthrough
    simulation_analyze_city_tiles --> simulation__act_row : fallthrough
    simulation__act_row --> simulation__act_col : fallthrough
    simulation__act_col --> simulation_compute_tile_value_at : Call compute_tile_value_at
    simulation__act_col --> simulation_store_metric_at : Call store_metric_at
    simulation__act_col --> simulation__act_check_factory : Branch BNE
    simulation__act_col --> simulation__act_house : Jmp JMP
    simulation__act_col --> simulation__act_check_factory : fallthrough
    simulation__act_check_factory --> simulation__act_check_police : Branch BNE
    simulation__act_check_factory --> simulation__act_factory : Jmp JMP
    simulation__act_check_factory --> simulation__act_check_police : fallthrough
    simulation__act_check_police --> simulation__act_check_fire : Branch BNE
    simulation__act_check_police --> simulation__act_police_jobs : Jmp JMP
    simulation__act_check_police --> simulation__act_check_fire : fallthrough
    simulation__act_check_fire --> simulation__act_other : Branch BNE
    simulation__act_check_fire --> simulation__act_fire_jobs : Jmp JMP
    simulation__act_check_fire --> simulation__act_other : fallthrough
    simulation__act_other --> simulation__act_next : Jmp JMP
    simulation__act_other --> simulation__act_house : fallthrough
    simulation__act_house --> buildings_get_tile_density_units : Call get_tile_density_units
    simulation__act_house --> simulation__act_value_loop : fallthrough
    simulation__act_value_loop --> simulation_add_to_land_value : Call add_to_land_value
    simulation__act_value_loop --> simulation__act_value_loop : Branch BNE
    simulation__act_value_loop --> simulation_load_metric_at : Call load_metric_at
    simulation__act_value_loop --> simulation__act_police : Branch BEQ
    simulation__act_value_loop --> simulation__act_store_park : Branch BCC
    simulation__act_value_loop --> simulation__act_store_park : fallthrough
    simulation__act_store_park --> simulation__act_police : fallthrough
    simulation__act_police --> simulation_load_metric_at : Call load_metric_at
    simulation__act_police --> simulation__act_fire : Branch BEQ
    simulation__act_police --> simulation__act_store_police : Branch BCC
    simulation__act_police --> simulation__act_store_police : fallthrough
    simulation__act_store_police --> simulation__act_fire : fallthrough
    simulation__act_fire --> simulation_load_metric_at : Call load_metric_at
    simulation__act_fire --> simulation__act_worker : Branch BEQ
    simulation__act_fire --> simulation__act_store_fire : Branch BCC
    simulation__act_fire --> simulation__act_store_fire : fallthrough
    simulation__act_store_fire --> simulation__act_worker : fallthrough
    simulation__act_worker --> simulation_mul_by_10 : Call mul_by_10
    simulation__act_worker --> simulation_add_to_worker_supply : Call add_to_worker_supply
    simulation__act_worker --> simulation__act_next : Jmp JMP
    simulation__act_worker --> simulation__act_factory : fallthrough
    simulation__act_factory --> buildings_get_tile_density_units : Call get_tile_density_units
    simulation__act_factory --> simulation_region_has_nonzero : Call region_has_nonzero
    simulation__act_factory --> simulation__act_next : Branch BEQ
    simulation__act_factory --> simulation_mul_by_10 : Call mul_by_10
    simulation__act_factory --> simulation_add_to_jobs : Call add_to_jobs
    simulation__act_factory --> simulation__act_next : Jmp JMP
    simulation__act_factory --> simulation__act_police_jobs : fallthrough
    simulation__act_police_jobs --> simulation_load_metric_at : Call load_metric_at
    simulation__act_police_jobs --> simulation__act_next : Branch BEQ
    simulation__act_police_jobs --> buildings_get_tile_density_units : Call get_tile_density_units
    simulation__act_police_jobs --> simulation_mul_by_2 : Call mul_by_2
    simulation__act_police_jobs --> simulation_add_to_jobs : Call add_to_jobs
    simulation__act_police_jobs --> simulation__act_next : Jmp JMP
    simulation__act_police_jobs --> simulation__act_fire_jobs : fallthrough
    simulation__act_fire_jobs --> simulation_load_metric_at : Call load_metric_at
    simulation__act_fire_jobs --> simulation__act_next : Branch BEQ
    simulation__act_fire_jobs --> buildings_get_tile_density_units : Call get_tile_density_units
    simulation__act_fire_jobs --> simulation_mul_by_2 : Call mul_by_2
    simulation__act_fire_jobs --> simulation_add_to_jobs : Call add_to_jobs
    simulation__act_fire_jobs --> simulation__act_next : fallthrough
    simulation__act_next --> simulation__act_next_row : Branch BEQ
    simulation__act_next --> simulation__act_col : Jmp JMP
    simulation__act_next --> simulation__act_next_row : fallthrough
    simulation__act_next_row --> simulation__act_done : Branch BEQ
    simulation__act_next_row --> simulation__act_row : Jmp JMP
    simulation__act_next_row --> simulation__act_done : fallthrough
    simulation_add_to_component_jobs --> simulation__acj_store : Branch BCC
    simulation_add_to_component_jobs --> simulation__acj_store : fallthrough
    simulation_add_to_component_workers --> simulation__acw_store : Branch BCC
    simulation_add_to_component_workers --> simulation__acw_store : fallthrough
    simulation_touches_current_road_component --> simulation__trc_south : Branch BEQ
    simulation_touches_current_road_component --> simulation_load_metric_at : Call load_metric_at
    simulation_touches_current_road_component --> simulation__trc_yes : Branch BEQ
    simulation_touches_current_road_component --> simulation__trc_south : fallthrough
    simulation__trc_south --> simulation__trc_east : Branch BCS
    simulation__trc_south --> simulation_load_metric_at : Call load_metric_at
    simulation__trc_south --> simulation__trc_yes : Branch BEQ
    simulation__trc_south --> simulation__trc_east : fallthrough
    simulation__trc_east --> simulation__trc_west : Branch BCS
    simulation__trc_east --> simulation_load_metric_at : Call load_metric_at
    simulation__trc_east --> simulation__trc_yes : Branch BEQ
    simulation__trc_east --> simulation__trc_west : fallthrough
    simulation__trc_west --> simulation__trc_no : Branch BEQ
    simulation__trc_west --> simulation_load_metric_at : Call load_metric_at
    simulation__trc_west --> simulation__trc_yes : Branch BEQ
    simulation__trc_west --> simulation__trc_no : fallthrough
    simulation_expand_current_road_component --> simulation__erc_pass : fallthrough
    simulation__erc_pass --> simulation__erc_row : fallthrough
    simulation__erc_row --> simulation__erc_col : fallthrough
    simulation__erc_col --> map_get_tile : Call get_tile
    simulation__erc_col --> simulation__erc_roadlike : Branch BEQ
    simulation__erc_col --> simulation__erc_next : Branch BNE
    simulation__erc_col --> simulation__erc_roadlike : fallthrough
    simulation__erc_roadlike --> simulation_load_metric_at : Call load_metric_at
    simulation__erc_roadlike --> simulation__erc_next : Branch BNE
    simulation__erc_roadlike --> simulation_touches_current_road_component : Call touches_current_road_component
    simulation__erc_roadlike --> simulation__erc_next : Branch BEQ
    simulation__erc_roadlike --> simulation_store_metric_at : Call store_metric_at
    simulation__erc_roadlike --> simulation__erc_next : fallthrough
    simulation__erc_next --> simulation__erc_next_row : Branch BEQ
    simulation__erc_next --> simulation__erc_col : Jmp JMP
    simulation__erc_next --> simulation__erc_next_row : fallthrough
    simulation__erc_next_row --> simulation__erc_pass_done : Branch BEQ
    simulation__erc_next_row --> simulation__erc_row : Jmp JMP
    simulation__erc_next_row --> simulation__erc_pass_done : fallthrough
    simulation__erc_pass_done --> simulation__erc_pass : Branch BNE
    simulation_mark_current_road_component_processed --> simulation__mrc_row : fallthrough
    simulation__mrc_row --> simulation__mrc_col : fallthrough
    simulation__mrc_col --> simulation_load_metric_at : Call load_metric_at
    simulation__mrc_col --> simulation__mrc_next : Branch BNE
    simulation__mrc_col --> simulation_store_metric_at : Call store_metric_at
    simulation__mrc_col --> simulation__mrc_next : fallthrough
    simulation__mrc_next --> simulation__mrc_next_row : Branch BEQ
    simulation__mrc_next --> simulation__mrc_col : Jmp JMP
    simulation__mrc_next --> simulation__mrc_next_row : fallthrough
    simulation__mrc_next_row --> simulation__mrc_done : Branch BEQ
    simulation__mrc_next_row --> simulation__mrc_row : Jmp JMP
    simulation__mrc_next_row --> simulation__mrc_done : fallthrough
    simulation_score_current_road_component --> simulation__src_row : fallthrough
    simulation__src_row --> simulation__src_col : fallthrough
    simulation__src_col --> map_get_tile : Call get_tile
    simulation__src_col --> simulation__src_not_empty : Branch BNE
    simulation__src_col --> simulation__src_next : Jmp JMP
    simulation__src_col --> simulation__src_not_empty : fallthrough
    simulation__src_not_empty --> simulation__src_not_water : Branch BNE
    simulation__src_not_empty --> simulation__src_next : Jmp JMP
    simulation__src_not_empty --> simulation__src_not_water : fallthrough
    simulation__src_not_water --> simulation__src_not_tree : Branch BNE
    simulation__src_not_water --> simulation__src_next : Jmp JMP
    simulation__src_not_water --> simulation__src_not_tree : fallthrough
    simulation__src_not_tree --> simulation_touches_current_road_component : Call touches_current_road_component
    simulation__src_not_tree --> simulation__src_connected : Branch BNE
    simulation__src_not_tree --> simulation__src_next : Jmp JMP
    simulation__src_not_tree --> simulation__src_connected : fallthrough
    simulation__src_connected --> simulation__src_factory : Branch BNE
    simulation__src_connected --> buildings_get_tile_density_units : Call get_tile_density_units
    simulation__src_connected --> simulation_mul_by_10 : Call mul_by_10
    simulation__src_connected --> simulation_add_to_component_workers : Call add_to_component_workers
    simulation__src_connected --> simulation__src_next : Jmp JMP
    simulation__src_connected --> simulation__src_factory : fallthrough
    simulation__src_factory --> simulation__src_police : Branch BNE
    simulation__src_factory --> buildings_get_tile_density_units : Call get_tile_density_units
    simulation__src_factory --> simulation_region_has_nonzero : Call region_has_nonzero
    simulation__src_factory --> simulation__src_next : Branch BEQ
    simulation__src_factory --> buildings_get_tile_density_units : Call get_tile_density_units
    simulation__src_factory --> simulation_mul_by_10 : Call mul_by_10
    simulation__src_factory --> simulation_add_to_component_jobs : Call add_to_component_jobs
    simulation__src_factory --> simulation__src_next : Jmp JMP
    simulation__src_factory --> simulation__src_police : fallthrough
    simulation__src_police --> simulation__src_fire : Branch BNE
    simulation__src_police --> simulation_load_metric_at : Call load_metric_at
    simulation__src_police --> simulation__src_next : Branch BEQ
    simulation__src_police --> buildings_get_tile_density_units : Call get_tile_density_units
    simulation__src_police --> simulation_mul_by_2 : Call mul_by_2
    simulation__src_police --> simulation_add_to_component_jobs : Call add_to_component_jobs
    simulation__src_police --> simulation__src_next : Jmp JMP
    simulation__src_police --> simulation__src_fire : fallthrough
    simulation__src_fire --> simulation__src_next : Branch BNE
    simulation__src_fire --> simulation_load_metric_at : Call load_metric_at
    simulation__src_fire --> simulation__src_next : Branch BEQ
    simulation__src_fire --> buildings_get_tile_density_units : Call get_tile_density_units
    simulation__src_fire --> simulation_mul_by_2 : Call mul_by_2
    simulation__src_fire --> simulation_add_to_component_jobs : Call add_to_component_jobs
    simulation__src_fire --> simulation__src_next : fallthrough
    simulation__src_next --> simulation__src_next_row : Branch BEQ
    simulation__src_next --> simulation__src_col : Jmp JMP
    simulation__src_next --> simulation__src_next_row : fallthrough
    simulation__src_next_row --> simulation__src_totals : Branch BEQ
    simulation__src_next_row --> simulation__src_row : Jmp JMP
    simulation__src_next_row --> simulation__src_totals : fallthrough
    simulation__src_totals --> simulation__src_done : Branch BEQ
    simulation__src_totals --> simulation__src_done : Branch BEQ
    simulation__src_totals --> simulation_add_to_jobs : Call add_to_jobs
    simulation__src_totals --> simulation__src_use_workers : Branch BCC
    simulation__src_totals --> simulation__src_add_employed : Jmp JMP
    simulation__src_totals --> simulation__src_use_workers : fallthrough
    simulation__src_use_workers --> simulation__src_add_employed : fallthrough
    simulation__src_add_employed --> simulation_add_to_worker_supply : Call add_to_worker_supply
    simulation__src_add_employed --> simulation__src_done : fallthrough
    simulation_analyze_road_networks --> simulation_clear_segment_totals : Call clear_segment_totals
    simulation_analyze_road_networks --> simulation__arn_row : fallthrough
    simulation__arn_row --> simulation__arn_col : fallthrough
    simulation__arn_col --> simulation_load_metric_at : Call load_metric_at
    simulation__arn_col --> simulation__arn_has_segments : Branch BNE
    simulation__arn_col --> simulation__arn_next : Jmp JMP
    simulation__arn_col --> simulation__arn_has_segments : fallthrough
    simulation__arn_has_segments --> map_get_tile : Call get_tile
    simulation__arn_has_segments --> simulation__arn_check_factory : Branch BNE
    simulation__arn_has_segments --> buildings_get_tile_density_units : Call get_tile_density_units
    simulation__arn_has_segments --> simulation_mul_by_10 : Call mul_by_10
    simulation__arn_has_segments --> simulation_add_workers_for_segments : Call add_workers_for_segments
    simulation__arn_has_segments --> simulation__arn_next : Jmp JMP
    simulation__arn_has_segments --> simulation__arn_check_factory : fallthrough
    simulation__arn_check_factory --> simulation__arn_check_police : Branch BNE
    simulation__arn_check_factory --> buildings_get_tile_density_units : Call get_tile_density_units
    simulation__arn_check_factory --> simulation_region_has_nonzero : Call region_has_nonzero
    simulation__arn_check_factory --> simulation__arn_next : Branch BEQ
    simulation__arn_check_factory --> buildings_get_tile_density_units : Call get_tile_density_units
    simulation__arn_check_factory --> simulation_mul_by_10 : Call mul_by_10
    simulation__arn_check_factory --> simulation_add_jobs_for_segments : Call add_jobs_for_segments
    simulation__arn_check_factory --> simulation__arn_next : Jmp JMP
    simulation__arn_check_factory --> simulation__arn_check_police : fallthrough
    simulation__arn_check_police --> simulation__arn_check_fire : Branch BNE
    simulation__arn_check_police --> simulation_load_metric_at : Call load_metric_at
    simulation__arn_check_police --> simulation__arn_next : Branch BEQ
    simulation__arn_check_police --> buildings_get_tile_density_units : Call get_tile_density_units
    simulation__arn_check_police --> simulation_mul_by_2 : Call mul_by_2
    simulation__arn_check_police --> simulation_add_jobs_for_segments : Call add_jobs_for_segments
    simulation__arn_check_police --> simulation__arn_next : Jmp JMP
    simulation__arn_check_police --> simulation__arn_check_fire : fallthrough
    simulation__arn_check_fire --> simulation__arn_next : Branch BNE
    simulation__arn_check_fire --> simulation_load_metric_at : Call load_metric_at
    simulation__arn_check_fire --> simulation__arn_next : Branch BEQ
    simulation__arn_check_fire --> buildings_get_tile_density_units : Call get_tile_density_units
    simulation__arn_check_fire --> simulation_mul_by_2 : Call mul_by_2
    simulation__arn_check_fire --> simulation_add_jobs_for_segments : Call add_jobs_for_segments
    simulation__arn_check_fire --> simulation__arn_next : fallthrough
    simulation__arn_next --> simulation__arn_next_row : Branch BEQ
    simulation__arn_next --> simulation__arn_col : Jmp JMP
    simulation__arn_next --> simulation__arn_next_row : fallthrough
    simulation__arn_next_row --> simulation__arn_totals : Branch BEQ
    simulation__arn_next_row --> simulation__arn_row : Jmp JMP
    simulation__arn_next_row --> simulation__arn_totals : fallthrough
    simulation__arn_totals --> simulation__arn_seg_loop : fallthrough
    simulation__arn_seg_loop --> simulation_add_to_jobs : Call add_to_jobs
    simulation__arn_seg_loop --> simulation__arn_seg_next : Branch BEQ
    simulation__arn_seg_loop --> simulation__arn_use_workers : Branch BCC
    simulation__arn_seg_loop --> simulation__arn_add_emp : Jmp JMP
    simulation__arn_seg_loop --> simulation__arn_use_workers : fallthrough
    simulation__arn_use_workers --> simulation__arn_add_emp : fallthrough
    simulation__arn_add_emp --> simulation_add_to_worker_supply : Call add_to_worker_supply
    simulation__arn_add_emp --> simulation__arn_seg_next : fallthrough
    simulation__arn_seg_next --> simulation__arn_seg_loop : Branch BNE
    simulation__arn_seg_next --> simulation__arn_done : fallthrough
    simulation_add_workers_for_segments --> simulation__awfs_high : Branch BEQ
    simulation_add_workers_for_segments --> simulation__awfs_store_low : Branch BCC
    simulation_add_workers_for_segments --> simulation__awfs_store_low : fallthrough
    simulation__awfs_store_low --> simulation__awfs_high : fallthrough
    simulation__awfs_high --> simulation__awfs_done : Branch BEQ
    simulation__awfs_high --> simulation__awfs_store_high : Branch BCC
    simulation__awfs_high --> simulation__awfs_store_high : fallthrough
    simulation__awfs_store_high --> simulation__awfs_done : fallthrough
    simulation_add_jobs_for_segments --> simulation__ajfs_high : Branch BEQ
    simulation_add_jobs_for_segments --> simulation__ajfs_store_low : Branch BCC
    simulation_add_jobs_for_segments --> simulation__ajfs_store_low : fallthrough
    simulation__ajfs_store_low --> simulation__ajfs_high : fallthrough
    simulation__ajfs_high --> simulation__ajfs_done : Branch BEQ
    simulation__ajfs_high --> simulation__ajfs_store_high : Branch BCC
    simulation__ajfs_high --> simulation__ajfs_store_high : fallthrough
    simulation__ajfs_store_high --> simulation__ajfs_done : fallthrough
    simulation_run_simulation --> simulation_mul_by_50 : Call mul_by_50
    simulation_run_simulation --> simulation_mul_by_5 : Call mul_by_5
    simulation_run_simulation --> simulation_mul_by_20 : Call mul_by_20
    simulation_run_simulation --> simulation__pwr_police : Branch BCC
    simulation_run_simulation --> simulation__pwr_police : fallthrough
    simulation__pwr_police --> simulation_mul_by_2 : Call mul_by_2
    simulation__pwr_police --> simulation__pwr_fire : Branch BCC
    simulation__pwr_police --> simulation__pwr_fire : fallthrough
    simulation__pwr_fire --> simulation_mul_by_2 : Call mul_by_2
    simulation__pwr_fire --> simulation__pwr_store : Branch BCC
    simulation__pwr_fire --> simulation__pwr_store : fallthrough
    simulation__pwr_store --> simulation__jobs : Branch BCS
    simulation__pwr_store --> simulation__jobs : fallthrough
    simulation__jobs --> simulation_build_service_maps : Call build_service_maps
    simulation__jobs --> simulation_analyze_city_tiles : Call analyze_city_tiles
    simulation__jobs --> simulation_analyze_road_networks : Call analyze_road_networks
    simulation__jobs --> simulation__jobs_overlap_ready : Branch BCC
    simulation__jobs --> simulation__jobs_overlap_ready : fallthrough
    simulation__jobs_overlap_ready --> simulation__all_employed : Branch BCC
    simulation__jobs_overlap_ready --> simulation__all_employed : Branch BEQ
    simulation__jobs_overlap_ready --> simulation__crime : Branch BNE
    simulation__jobs_overlap_ready --> simulation__all_employed : fallthrough
    simulation__all_employed --> simulation__crime : fallthrough
    simulation__crime --> simulation_mul_by_2 : Call mul_by_2
    simulation__crime --> simulation__crime_cap : Branch BCS
    simulation__crime --> simulation__crime_blackout : Branch BCC
    simulation__crime --> simulation__crime_cap : fallthrough
    simulation__crime_cap --> simulation__crime_blackout : fallthrough
    simulation__crime_blackout --> simulation__crime_police : Branch BEQ
    simulation__crime_blackout --> simulation__crime_store_blackout : Branch BCC
    simulation__crime_blackout --> simulation__crime_store_blackout : fallthrough
    simulation__crime_store_blackout --> simulation__crime_police : fallthrough
    simulation__crime_police --> simulation__crime_sub_police : Branch BCS
    simulation__crime_police --> simulation__crime_fire : Branch BEQ
    simulation__crime_police --> simulation__crime_sub_police : fallthrough
    simulation__crime_sub_police --> simulation__crime_fire : fallthrough
    simulation__crime_fire --> simulation__crime_sub_fire : Branch BCS
    simulation__crime_fire --> simulation__crime_parks : Branch BEQ
    simulation__crime_fire --> simulation__crime_sub_fire : fallthrough
    simulation__crime_sub_fire --> simulation__crime_parks : fallthrough
    simulation__crime_parks --> simulation__crime_sub_parks : Branch BCS
    simulation__crime_parks --> simulation__happiness : Branch BEQ
    simulation__crime_parks --> simulation__crime_sub_parks : fallthrough
    simulation__crime_sub_parks --> simulation__crime_done : fallthrough
    simulation__crime_done --> simulation__happiness : fallthrough
    simulation__happiness --> simulation__hap_store_parks : Branch BCC
    simulation__happiness --> simulation__hap_store_parks : fallthrough
    simulation__hap_store_parks --> simulation__hap_store_police : Branch BCC
    simulation__hap_store_parks --> simulation__hap_store_police : fallthrough
    simulation__hap_store_police --> simulation__hap_store_fire : Branch BCC
    simulation__hap_store_police --> simulation__hap_store_fire : fallthrough
    simulation__hap_store_fire --> simulation__hap_store_value : Branch BCC
    simulation__hap_store_fire --> simulation__hap_store_value : fallthrough
    simulation__hap_store_value --> simulation__hap_job_bonus : Branch BEQ
    simulation__hap_store_value --> simulation_mul_by_2 : Call mul_by_2
    simulation__hap_store_value --> simulation__hap_sub_unemp : Branch BCS
    simulation__hap_store_value --> simulation__hap_blackout : Branch BEQ
    simulation__hap_store_value --> simulation__hap_sub_unemp : fallthrough
    simulation__hap_sub_unemp --> simulation__hap_job_bonus : fallthrough
    simulation__hap_job_bonus --> simulation__hap_blackout : Branch BEQ
    simulation__hap_job_bonus --> simulation__hap_blackout : Branch BNE
    simulation__hap_job_bonus --> simulation__hap_store_bonus : Branch BCC
    simulation__hap_job_bonus --> simulation__hap_store_bonus : fallthrough
    simulation__hap_store_bonus --> simulation__hap_blackout : fallthrough
    simulation__hap_blackout --> simulation__hap_crime : Branch BEQ
    simulation__hap_blackout --> simulation__hap_sub_blackout : Branch BCS
    simulation__hap_blackout --> simulation__hap_crime : Branch BEQ
    simulation__hap_blackout --> simulation__hap_sub_blackout : fallthrough
    simulation__hap_sub_blackout --> simulation__hap_crime : fallthrough
    simulation__hap_crime --> simulation__hap_sub_crime : Branch BCS
    simulation__hap_crime --> simulation__economy : Branch BEQ
    simulation__hap_crime --> simulation__hap_sub_crime : fallthrough
    simulation__hap_sub_crime --> simulation__economy : fallthrough
    simulation__economy --> simulation_mul_by_2 : Call mul_by_2
    simulation__economy --> simulation_add_to_revenue : Call add_to_revenue
    simulation__economy --> simulation_mul_by_2 : Call mul_by_2
    simulation__economy --> simulation_add_to_revenue : Call add_to_revenue
    simulation__economy --> simulation_add_to_revenue : Call add_to_revenue
    simulation__economy --> simulation_add_to_revenue : Call add_to_revenue
    simulation__economy --> simulation_mul_by_20 : Call mul_by_20
    simulation__economy --> simulation_add_to_revenue : Call add_to_revenue
    simulation__economy --> simulation_add_to_cost : Call add_to_cost
    simulation__economy --> simulation_add_to_cost : Call add_to_cost
    simulation__economy --> simulation_mul_by_5 : Call mul_by_5
    simulation__economy --> simulation_add_to_cost : Call add_to_cost
    simulation__economy --> simulation_mul_by_5 : Call mul_by_5
    simulation__economy --> simulation_add_to_cost : Call add_to_cost
    simulation__economy --> simulation_mul_by_20 : Call mul_by_20
    simulation__economy --> simulation_add_to_cost : Call add_to_cost
    simulation__economy --> simulation_mul_by_10 : Call mul_by_10
    simulation__economy --> simulation_add_to_cost : Call add_to_cost
    simulation__economy --> simulation_mul_by_10 : Call mul_by_10
    simulation__economy --> simulation_add_to_cost : Call add_to_cost
    simulation__economy --> simulation_mul_by_2 : Call mul_by_2
    simulation__economy --> simulation_add_to_cost : Call add_to_cost
    simulation__economy --> simulation__apply_net : Branch BEQ
    simulation__economy --> simulation_add_to_cost : Call add_to_cost
    simulation__economy --> simulation__apply_net : fallthrough
    simulation__apply_net --> simulation__money_floor_ok : Branch BPL
    simulation__apply_net --> ui_print_str_col : Call print_str_col
    simulation__apply_net --> simulation__money_floor_ok : fallthrough
    simulation__money_floor_ok --> simulation__money_ceil_ok : Branch BPL
    simulation__money_floor_ok --> simulation__money_ceil_ok : fallthrough
    simulation__money_ceil_ok --> simulation_mul_by_10 : Call mul_by_10
    simulation__money_ceil_ok --> simulation__pop_jobs_ok : Branch BCC
    simulation__money_ceil_ok --> simulation__pop_jobs_ok : fallthrough
    simulation__pop_jobs_ok --> simulation__pop_target_ready : Branch BCC
    simulation__pop_jobs_ok --> simulation__pop_target_ready : fallthrough
    simulation__pop_target_ready --> simulation__pop_balance : Branch BEQ
    simulation__pop_target_ready --> simulation__pop_shrink : Branch BCS
    simulation__pop_target_ready --> simulation__pop_done : Branch BCC
    simulation__pop_target_ready --> simulation__pop_done : Branch BNE
    simulation__pop_target_ready --> simulation__pop_shrink : fallthrough
    simulation__pop_shrink --> simulation__pop_do_shrink : Branch BCC
    simulation__pop_shrink --> simulation__pop_done : Branch BEQ
    simulation__pop_shrink --> simulation__pop_do_shrink : fallthrough
    simulation__pop_do_shrink --> simulation__pop_done : Branch BEQ
    simulation__pop_do_shrink --> simulation__pop_done : Branch BNE
    simulation__pop_do_shrink --> simulation__pop_balance : fallthrough
    simulation__pop_balance --> simulation__pop_done : Branch BCS
    simulation__pop_balance --> simulation__pop_done : Branch BEQ
    simulation__pop_balance --> simulation__pop_done : fallthrough
    simulation__pop_done --> simulation__no_year : Branch BNE
    simulation__pop_done --> simulation__no_year : Branch BNE
    simulation__pop_done --> simulation__no_year : fallthrough
